a = [
  {
    title: "Python Programming: A Modular Approach",
    authors: ["naveen ", "kumar and taneja sheetal"],
    description: None,
    publisher: "Pearson Education, 2017",
    isbn: "9789332585348",
    thumbnail: "https://pictures.abebooks.com/isbn/9789332585348-us.jpg",
  },
  {
    title: "Python Programming: A Modular Approach",
    authors: ["naveen ", "kumar and taneja sheetal"],
    description: None,
    publisher: "Pearson Education, 2017",
    isbn: "9789332585348",
    thumbnail: "https://pictures.abebooks.com/isbn/9789332585348-us.jpg",
  },
  {
    title: "Python Programming: A Modular Approach",
    authors: ["naveen", " kumar and taneja sheetal"],
    description: None,
    publisher: "Pearson, 2017",
    isbn: "9789332585348",
    thumbnail: "https://pictures.abebooks.com/isbn/9789332585348-us.jpg",
  },
  {
    title: "Python Programming A modular approach By Pearson",
    authors: ["taneja sheeta and kumar naveen"],
    description: "None",
    publisher: "None",
    isbn: None,
    thumbnail: "https://pictures.abebooks.com/inventory/md/md31072929255.jpg",
  },
  {
    title: "PYTHON PROGRAMMING: A MODULAR APPROACH",
    authors: ["naveen ", "kumar and taneja sheetal"],
    description: None,
    publisher: "PEARSON INDIA, 2017",
    isbn: "9789332585348",
    thumbnail:
      "//assets.prod.abebookscdn.com/cdn/com/images/servlets/shared/international-edition.gif",
  },
  {
    title: "Python Programming: A Modular Approach",
    authors: ["naveen ", "kumar and taneja sheetal"],
    description: None,
    publisher: "PEARSON INDIA, 2017",
    isbn: "9789332585348",
    thumbnail: "https://pictures.abebooks.com/isbn/9789332585348-us.jpg",
  },
  {
    title: "Python Programming: A Modular Approach",
    authors: ["naveen ", "kumar and taneja sheetal"],
    description: None,
    publisher: "PEARSON INDIA, 2017",
    isbn: "9789332585348",
    thumbnail: "https://pictures.abebooks.com/isbn/9789332585348-us.jpg",
  },
  {
    title: "Python Programming: A Modular Approach",
    authors: ["naveen ", "kumar and taneja sheetal"],
    description: None,
    publisher: "PEARSON INDIA, 2017",
    isbn: "9789332585348",
    thumbnail: "https://pictures.abebooks.com/isbn/9789332585348-us.jpg",
  },
  {
    title: "Python Programming: A Modular Approach",
    authors: ["naveen ", "kumar and taneja sheetal"],
    description: None,
    publisher: "PEARSON INDIA, 2017",
    isbn: "9789332585348",
    thumbnail: "https://pictures.abebooks.com/isbn/9789332585348-us.jpg",
  },
  {
    title: "PYTHON PROGRAMMING: A MODULAR APPROACH",
    authors: ["naveen ", "kumar and taneja sheetal"],
    description: None,
    publisher: "PEARSON INDIA, 2017",
    isbn: "9789332585348",
    thumbnail:
      "//assets.prod.abebookscdn.com/cdn/com/images/servlets/shared/international-edition.gif",
  },
  {
    title: "Python Programming: A Modular Approach",
    authors: ["naveen ", "kumar and taneja sheetal"],
    description: None,
    publisher: "PEARSON INDIA, 2017",
    isbn: "9789332585348",
    thumbnail:
      "//assets.prod.abebookscdn.com/cdn/com/images/servlets/shared/international-edition.gif",
  },
  {
    title: "Python Programming: A Modular Approach",
    authors: ["naveen ", "kumar and taneja sheetal"],
    description: None,
    publisher: "PEARSON INDIA, 2017",
    isbn: "9789332585348",
    thumbnail:
      "//assets.prod.abebookscdn.com/cdn/com/images/servlets/shared/international-edition.gif",
  },
  {
    title: "Python Programming: A Modular Approach",
    authors: ["naveen ", "kumar and taneja sheetal"],
    description: None,
    publisher: "PEARSON INDIA, 2017",
    isbn: "9789332585348",
    thumbnail: "https://pictures.abebooks.com/isbn/9789332585348-us.jpg",
  },
  {
    title: "Python Programming: A Modular Approach",
    authors: ["naveen ", "kumar and taneja sheetal"],
    description: None,
    publisher: "PEARSON INDIA, 2017",
    isbn: "9789332585348",
    thumbnail: "https://pictures.abebooks.com/isbn/9789332585348-us.jpg",
  },
  {
    title: "Python Programming: A Modular Approach - Softcover",
    authors: ["naveen ", "kumar and taneja sheetal"],
    description: None,
    publisher: "PEARSON INDIA",
    isbn: "9789332585348",
    thumbnail: "https://pictures.abebooks.com/isbn/9789332585348-us.jpg",
  },
  {
    title: "Python Programming: A Modular Approach - Softcover",
    authors: ["naveen ", "kumar and taneja sheetal"],
    description: None,
    publisher: "PEARSON INDIA",
    isbn: "9789332585348",
    thumbnail: "https://pictures.abebooks.com/isbn/9789332585348-us.jpg",
  },
  {
    title: "Python Programming: A Modular Approach - Softcover",
    authors: ["naveen ", "kumar and taneja sheetal"],
    description: None,
    publisher: "PEARSON INDIA",
    isbn: "9789332585348",
    thumbnail: "https://pictures.abebooks.com/isbn/9789332585348-us.jpg",
  },
  {
    title: "Python Programming: A Modular Approach - Softcover",
    authors: ["naveen ", "kumar and taneja sheetal"],
    description: None,
    publisher: "PEARSON INDIA",
    isbn: "9789332585348",
    thumbnail: "https://pictures.abebooks.com/isbn/9789332585348-us.jpg",
  },
  {
    title: "Python Programming: A Modular Approach - Softcover",
    authors: ["naveen ", "kumar and taneja sheetal"],
    description: None,
    publisher: "PEARSON INDIA",
    isbn: "9789332585348",
    thumbnail: "https://pictures.abebooks.com/isbn/9789332585348-us.jpg",
  },
  {
    title: "Python Programming: A Modular Approach - Softcover",
    authors: ["naveen ", "kumar and taneja sheetal"],
    description: None,
    publisher: "PEARSON INDIA",
    isbn: "9789332585348",
    thumbnail: "https://pictures.abebooks.com/isbn/9789332585348-us.jpg",
  },
  {
    title: "Python Programming: A Modular Approach - Softcover",
    authors: ["naveen ", "kumar and taneja sheetal"],
    description: None,
    publisher: "PEARSON INDIA",
    isbn: "9789332585348",
    thumbnail: "https://pictures.abebooks.com/isbn/9789332585348-us.jpg",
  },
  {
    title: "Python Programming: A Modular Approach - Softcover",
    authors: ["naveen ", "kumar and taneja sheetal"],
    description: None,
    publisher: "PEARSON INDIA",
    isbn: "9789332585348",
    thumbnail: "https://pictures.abebooks.com/isbn/9789332585348-us.jpg",
  },
  {
    title: "Python Programming: A Modular Approach - Softcover",
    authors: ["naveen ", "kumar and taneja sheetal"],
    description: None,
    publisher: "PEARSON INDIA",
    isbn: "9789332585348",
    thumbnail: "https://pictures.abebooks.com/isbn/9789332585348-us.jpg",
  },
  {
    title: "Python Programming: A Modular Approach - Softcover",
    authors: ["naveen ", "kumar and taneja sheetal"],
    description: None,
    publisher: "PEARSON INDIA",
    isbn: "9789332585348",
    thumbnail: "https://pictures.abebooks.com/isbn/9789332585348-us.jpg",
  },
  {
    title: "Python Programming: A Modular Approach - Softcover",
    authors: ["naveen ", "kumar and taneja sheetal"],
    description: None,
    publisher: "PEARSON INDIA",
    isbn: "9789332585348",
    thumbnail: "https://pictures.abebooks.com/isbn/9789332585348-us.jpg",
  },
  {
    title: "Python Programming: A Modular Approach - Softcover",
    authors: ["naveen ", "kumar and taneja sheetal"],
    description: None,
    publisher: "PEARSON INDIA",
    isbn: "9789332585348",
    thumbnail: "https://pictures.abebooks.com/isbn/9789332585348-us.jpg",
  },
  {
    title: "Python Programming: A Modular Approach - Softcover",
    authors: ["naveen ", "kumar and taneja sheetal"],
    description: None,
    publisher: "PEARSON INDIA",
    isbn: "9789332585348",
    thumbnail: "https://pictures.abebooks.com/isbn/9789332585348-us.jpg",
  },
];
